# version: '3.8'

services:
  traefik:
    image: traefik:latest
    networks:
      - proxy
    command:
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.http.tls=true"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      # Let's Encrypt configuration
      - "--certificatesresolvers.le.acme.email=jherhum1702@g.educaand.es"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "./letsencrypt:/letsencrypt"

  api:
    image: hernande/devops-03:latest
    expose:
      - "8000"
    networks:
      - proxy
      - backend
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.gimmeabis.tech`)"
      - "traefik.http.routers.fastapi.entrypoints=websecure"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=le"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8000"
      # Headers Middleware
      - "traefik.http.middlewares.secure-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.secure-headers.headers.sslRedirect=true"
      - "traefik.http.middlewares.secure-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.secure-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.secure-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.secure-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.secure-headers.headers.stsSeconds=31536000"
      # Apply middlewares to fastapi router
      - "traefik.http.routers.fastapi.middlewares=secure-headers"

  db:
    image:  mariadb #  mysql
    # container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s
  # NO VOY A EXPONER ESTO

  adminer:
    image: adminer
    restart: always
    networks:
      - backend
  # NO VOY A EXPONER ESTO

networks:
  proxy:
    name: proxy
  backend:

volumes:
  db_data: